<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://apache.org"
         xmlns:xsi="http://w3.org"
         xsi:schemaLocation="http://apache.org http://apache.org">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ashamesh</groupId>
    <artifactId>ashamesh-master-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>


    <modules>
        <module>eureka-server</module>
        <module>api-gateway</module>
        <module>sos-service</module>
    </modules>
</project>
